import Providers from "@/tools/Providers";
import "./globals.css";

export const metadata = {
  title: "Login page Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en" dir="rtl">
        <body>{children}</body>
      </html>
    </Providers>
  );
}
